PL/Controllers/MaterialsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using BL.Services.Interfaces;
using BL.DTO;
using AutoMapper;
using PL.Models;
using Microsoft.AspNetCore.Authorization;

namespace PL.Controllers
{
    /// <summary>
    /// This controller is for users and admins.
    /// It allows you to see all materials stored in database
    /// </summary>
    [Authorize(Roles = "admin, user")]
    public class MaterialsController : Controller
    {
        private readonly IMaterialService _materialService;

        public MaterialsController(IMaterialService serv)
        {
            _materialService = serv;
        }

        /// <summary>
        /// This method returns view of MaterialModel with all materials in it (from business layer)
        /// </summary>
        public IActionResult Index()
        {
            IEnumerable<MaterialDTO> materialDtos = _materialService.GetMaterials();
            var mapper   = new MapperConfiguration(cfg => cfg.CreateMap<MaterialDTO, MaterialViewModel>()).CreateMapper();
            var materials = mapper.Map<IEnumerable<MaterialDTO>, List<MaterialViewModel>>(materialDtos);

            if (materials != null)
            {
                return View(materials);
            }
            else
            {
                return NotFound();
            }
        }

	}
}

PL/Controllers/UsersController.cs
using BL.DTO;
using Microsoft.AspNetCore.Mvc;
using BL.Services.Interfaces;
using PL.Models;
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using System;

namespace PL.Controllers
{
    /// <summary>
    /// This controller is for users and admins.
    /// It allows you to see all materials stored in database
    /// </summary>
    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        private readonly IUserService _userService;
        private readonly IPasswordService _password;
        private readonly IEmailService _email;
        private readonly IRoleService _role;

        public UsersController(IUserService serv, IPasswordService passwordService, IEmailService emailService, IRoleService roleService)
        {
            _userService = serv;
            _password = passwordService;
            _email = emailService;
            _role = roleService;
        }

        /// <summary>
        /// This method fill table with users, if they exist, from business layer
        /// </summary>
        public ActionResult Index()
        {
            IEnumerable<UserDTO> userDtos = _userService.GetUsers();
            var mapperUser = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserDetailsViewModel>()).CreateMapper();
            var users = mapperUser.Map<IEnumerable<UserDTO>, List<UserDetailsViewModel>>(userDtos);

            if (users != null)
            {
                return View(users);
            }
            else
            {
                return NotFound();
            }
        }

        /// <summary>
        /// This method return view model for UsersModel to create
        /// </summary>
        public ActionResult Create()
        {
            if (User.IsInRole("admin"))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// This method sends new data for new user in business layer
        /// </summary>
        [HttpPost]
        public ActionResult Create(UserDetailsViewModel model)
        {
            if (ModelState.IsValid)
            {
                bool existErrors = false;

                if (!_userService.IsEmailFree(model.Email))
                {
                    ModelState.AddModelError("", "This email is already busy");
                    existErrors = true;
                }
                if (!_email.ValideEmail(model.Email))
                {
                    ModelState.AddModelError("", "This email is not valid");
                    existErrors = true;
                }

                if(!_role.IsAdmin(model.Role) && !_role.IsUser(model.Role))
                {
                    ModelState.AddModelError("", "There are only this roles: 'user' and 'admin'");
                    existErrors = true;
                }
                if (!_password.IsPasswordStrong(model.Password))
                {
                    ModelState.AddModelError("", "Password is too weak");
                    existErrors = true;
                }

                if (existErrors)
                {
                    return View(model);
                }

                var userDto = new UserDTO {
                    Name       = model.Name,
                    Surname    = model.Surname,
                    Role       = model.Role,
                    Login      = model.Login,
                    Email      = model.Email, 
                    Password   = model.Password,
                    DateRegist = DateTime.Now,
                };

                _userService.SaveUser(userDto);

                TempData["message"] = string.Format("New user \"{0}\" \"{1}\" with email \"{2}\" has been saved", model.Name, model.Surname, model.Email);

                return View(model);
            }
            return View(model);
            
        }
    }
}

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web-Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/Content/ErrorStyles.css" />
</head>
<body>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Card Files</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <partial name="_LoginPartial" />

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        }
                        @if (User.IsInRole("admin") || User.IsInRole("user"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Materials" asp-action="Index">Materials</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-black-50 disabled" asp-area="" asp-controller="Materials" asp-action="Index">Materials</a>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                            </li>
                        }
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
        
    <main role="main" class="pb-3">
        @RenderBody()
        @*@section Scripts
        {
            <partial name="_ValidationScriptsPartial" />
        }*@
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p class="float-right">
                <a href="#">Back to top</a>
            </p>
            <p>
                &copy; 2021 - Web project topic: Card file of text materials - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <partial name="_ValidationScriptsPartial" />

</body>
</html>